apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxy
  labels:
    app: istio
    release: komplete-prometheus
spec:
  namespaceSelector:
    matchNames:
    - cmpt756e4
  selector:
    matchExpressions:
    - key: app
      operator: Exists
  endpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
