services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      # At runtime, ${HWD} will be replaced with path in
      # Host OS filesystem to root CMPT 756 directory
      - "${HWD}/ci/docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  cmpt756db:
    image: "ghcr.io/tedkirkpatrick/cmpt756db:v1"
    container_name: cmpt756db
    ports:
      - "30002:30002"
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: 'DUMMY_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'DUMMY_ACCESS_ KEY'
      SVC_LOADER_TOKEN: 'DUMMY_LOADER_TOKEN'
      DYNAMODB_URL: 'http://dynamodb-local:8000'
  s1:
    depends_on:
      - dynamodb-local
      - db
    image: "ZZ-CR-ID/ZZ-REG-ID/cmpt756s1:v1"
    container_name: s1
    ports:
     - "30000:30000"
    environment:
      EXER: v1
  s2:
    depends_on:
      - dynamodb-local
      - db
    image: "ZZ-CR-ID/ZZ-REG-ID/cmpt756s2:v1"
    container_name: s2
    ports:
     - "30001:30001"
    environment:
      EXER: v1
  test:
    command: "python ci_test.py s1 30000 s2 30001"
    depends_on:
      - dynamodb-local
      - db
      - s1
      - s2
    image: "ZZ-CR-ID/ZZ-REG-ID/ci_test:v1"
    container_name: test

